"""Compatibility layer for the public data operation API."""

from data_ops import (
    AnalysisResult,
    DataFrameMap,
    DataSummary,
    SIGNAL_FILTER_OPERATIONS,
    add_derived_column,
    analyze_selected_dataframes,
    apply_signal_filter,
    apply_simple_filter,
    build_correlation_frame,
    build_statistics_frame,
    drop_dataframe_columns,
    drop_dataframe_index_range,
    export_clean_dataframes,
    merge_selected_dataframes,
    normalize_index_range,
    resolve_filtered_column_name,
    select_dataframe_columns,
    slice_dataframe_by_index_range,
    split_dataframe_by_index_ranges,
    subset_dataframe_rows,
    summarize_dataframe,
)

__all__ = [
    "AnalysisResult",
    "DataFrameMap",
    "DataSummary",
    "SIGNAL_FILTER_OPERATIONS",
    "add_derived_column",
    "analyze_selected_dataframes",
    "apply_signal_filter",
    "apply_simple_filter",
    "build_correlation_frame",
    "build_statistics_frame",
    "drop_dataframe_columns",
    "drop_dataframe_index_range",
    "export_clean_dataframes",
    "merge_selected_dataframes",
    "normalize_index_range",
    "resolve_filtered_column_name",
    "select_dataframe_columns",
    "slice_dataframe_by_index_range",
    "split_dataframe_by_index_ranges",
    "subset_dataframe_rows",
    "summarize_dataframe",
]